# Generated by Django 5.1.6 on 2025-03-13 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('session_date', models.DateTimeField()),
                ('session_updated_at', models.DateTimeField(auto_now=True)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('session_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_gateway_ref', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session_date', 'tutor'],
                'constraints': [models.UniqueConstraint(fields=('session_date', 'tutor'), name='unique_session_per_tutor')],
            },
        ),
    ]
