# Generated by Django 5.1.6 on 2025-04-07 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_student_alter_review_unique_together'),
        ('users', '0009_alter_tutorprofile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_time', 'tutor'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_session_per_tutor',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='session_end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tutor',
        ),
        migrations.AlterField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.tutorprofile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.tutorprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_booking', to='bookings.availability'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('start_time', 'tutor'), name='unique_time_slot'),
        ),
    ]
