# Generated by Django 5.1.6 on 2025-03-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='info_category',
            field=models.CharField(blank=True, choices=[('general', 'General Information'), ('system', 'System Update')], default='general', max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_title',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=127),
        ),
    ]
