
# Generated by Django 5.1.6 on 2025-03-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_info_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='info_category',
            field=models.CharField(blank=True, choices=[('general', 'General Information'), ('system', 'System Update')], default='general', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
    ]
