# Generated by Django 5.1.6 on 2025-04-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_priority'),
        ('notifications', '0005_notification_sender'),
    ]

    operations = [
    ]
