# Generated by Django 5.1.6 on 2025-03-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tutorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
