# Generated by Django 5.1.6 on 2025-03-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_tutorprofile_location_tutorprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
