# Generated by Django 5.1.6 on 2025-03-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tutorprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='zipcode',
        ),
    ]
