# Generated by Django 5.1.6 on 2025-03-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_tutorprofile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='state',
            field=models.CharField(default='NA', max_length=2),
        ),
    ]
