# Generated by Django 5.1.6 on 2025-03-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('users', '0006_alter_tutorprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(to='search.subject'),
        ),
    ]
