# Generated by Django 5.1.6 on 2025-03-16 21:26

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subject_tutorprofile_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(default=apps.users.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.category'),
        ),
    ]
