# Generated by Django 5.1.6 on 2025-03-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tutorprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
