# Generated by Django 5.1.6 on 2025-03-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tutorprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
