# Generated by Django 5.1.6 on 2025-04-05 23:10

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_alter_subject_table"),
        ("users", "0009_alter_tutorprofile_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(default="1234567890", max_length=15),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("none", "None"),
                ],
                default="email",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(12),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_phone_number", models.CharField(max_length=15)),
                (
                    "parent_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.parentprofile",
                    ),
                ),
                ("preferred_subjects", models.ManyToManyField(to="search.subject")),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
    ]
