# Generated by Django 5.1.6 on 2025-03-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_filtercriteria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterCriteria',
        ),
    ]
