# Generated by Django 5.1.6 on 2025-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_date_of_birth_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent_of',
            field=models.ManyToManyField(blank=True, related_name='parents', to='users.profile'),
        ),
    ]
