# Generated by Django 5.1.6 on 2025-04-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_subject_table'),
        ('users', '0010_profile_date_of_birth_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_phone_number',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_subjects',
            field=models.ManyToManyField(blank=True, to='search.subject'),
        ),
    ]
