# Generated by Django 5.1.6 on 2025-04-23 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_tutorprofile_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parentprofile'),
        ),
    ]
