# Generated by Django 5.1.6 on 2025-04-30 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_parent_of'),
        ('users', '0013_alter_studentprofile_parent_profile'),
    ]

    operations = [
    ]
