"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
# Import dj-database-url at the beginning of the file.
import dj_database_url
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
import cloudinary
from urllib.parse import urlparse

load_dotenv() # load environment variable file (tokens, keys, etc)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"] # allow all hosts for now...

# for working with JWT tokens
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# specify lifetimes for the JWT tokens
# refresh token should have a larger expiration date than the access token
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_extensions',
    "daphne",           #daphne has to be before django.contrib.staticfiles
    'django.contrib.staticfiles',
    "apps.api",         # our api app
    "apps.users",         # our users app
    "apps.pomodoro",      # our pomodoro app
    "apps.lessons",       # our lessons app
    "apps.submissions",   # our submissions app
    "apps.bookings",    # our bookings app
    "apps.notifications", # our notifications app
    "apps.chat",          # our chat app
    "apps.uploads",       # our uploads app
    "apps.search",        # our search app
    "apps.whiteboard",      # our whiteboard app
    "apps.sessions",        # our sessions app
    "apps.planner",       # our calendar app
    "apps.achievements",  # our achievements app
    "rest_framework",     # rest framework
    'rest_framework_simplejwt.token_blacklist', # for logout functionality
    "channels",           # Django channels
    "django_celery_results", # get celery results in Django admin
    "django_celery_beat", # celery beat
    "watson",
    "corsheaders",         # cors -> handle different origins (?)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'watson.middleware.SearchContextMiddleware', # for django-watson indexing
    "corsheaders.middleware.CorsMiddleware",  # for cors (added)
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# Replace the SQLite DATABASES configuration with PostgreSQL:
DATABASES = {
    'default': dj_database_url.config(
        # Replace this value with your local database's connection string.
        default='postgresql://postgres:postgres@localhost:5432/mysite',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
#STATIC_URL = 'static/'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# This setting informs Django of the URI path from which your static files will be served to users
# Here, they well be accessible at your-domain.onrender.com/static/... or yourcustomdomain.com/static/...
STATIC_URL = '/static/'

# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True   # typically allow specific origin, but dw for neow
CORS_ALLOW_CREDENTIALS = True   # allow credentials

#Celery Configurations
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'django-db'  # Required for django-celery-results
CELERY_TIMEZONE = 'UTC'

# CELERY BEAT SCHEDULER
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# REDIS CACHE
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

#ASGI App (needed for Django Channels to work)
ASGI_APPLICATION = "backend.asgi.application"

# For Production

# Get the REDIS_HOST environment variable or default to 'redis://127.0.0.1:6379'
redis_url = os.getenv('REDIS_HOST', 'redis://127.0.0.1:6379')

# Parse the Redis URL
parsed_url = urlparse(redis_url)

# Extract the host and port from the parsed URL
host = parsed_url.hostname
port = parsed_url.port  # 6379

# Configure the CHANNEL_LAYERS setting with the parsed host and port
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(host, port)],  # Use parsed host and port
        },
    },
}

#CHANNEL_LAYERS = {
#      "default": {
#          "BACKEND": "channels_redis.core.RedisChannelLayer",
#          "CONFIG": {
#              "hosts": [('127.0.0.1', 6379)],
#          },
#      },
    #"default": {
    #    "BACKEND": "channels.layers.InMemoryChannelLayer",
    #},
#}


# cloudinary
cloudinary.config(
  CLOUD_NAME = str(os.getenv('CLOUDINARY_CLOUD_NAME')),
  API_KEY= str(os.getenv('CLOUDINARY_API_KEY')),
  API_SECRET= str(os.getenv('CLOUDINARY_API_SECRET')),
)

# Standard session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_NAME = 'sessionid'  # Default session cookie name
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Set to 'None' for cross-site usage (requires Secure=True)
