# Generated by Django 5.1.6 on 2025-03-04 19:41

import cloudinary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(max_length=1000)),
                ('upload', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
    ]
