# Generated by Django 5.1.6 on 2025-03-04 20:08

import django.db.models.deletion
from django.db import migrations, models

def generate_profile(apps, schema):
    upload_record_model = apps.get_model('uploads', 'UploadRecord')
    for upload in upload_record_model.objects.all():
        upload.profile = f"{upload.name.replace(' ', '-')}-{upload.id}"
        upload.save()


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecord',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.RunPython(generate_profile),
        migrations.AlterField(
            model_name='uploadrecord',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
