# Generated by Django 5.1.6 on 2025-03-09 04:04

from django.db import migrations, models

def generate_asset_id(apps, schema):
    upload_record = apps.get_model('uploads', 'UploadRecord')
    for upload in upload_record.objects.all():
        upload.asset_id = f"{upload.file_name.replace(' ', '-')}-{upload.public_id}"
        upload.save()

class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecord',
            name='asset_id',
            field=models.CharField(max_length=255, null=True),
        ),
        # add this below with your function to populate the field
        migrations.RunPython(generate_asset_id),
        migrations.AlterField(
            model_name='uploadrecord',
            name='asset_id',
            field=models.CharField(max_length=255),
        ),
    ]
