# Generated by Django 5.1.6 on 2025-03-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadrecord_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecord',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
