# Generated by Django 5.1.6 on 2025-03-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadrecord_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrecord',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
