# Generated by Django 5.1.6 on 2025-03-05 05:09

from django.db import migrations, models

def generate_non_nullable_fields(apps, schema):
    upload_record_model = apps.get_model('uploads', 'UploadRecord')
    for upload in upload_record_model.objects.all():
        upload.profile = f"{upload.name.replace(' ', '-')}-{upload.id}"
        upload.save()

class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_uploadrecord_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrecord',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='file_format',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='public_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),

        # add this below with your function to populate the field
        migrations.RunPython(generate_non_nullable_fields),

        migrations.AlterField(
            model_name='uploadrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='file_format',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='public_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
