# Generated by Django 5.1.6 on 2025-03-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_remove_uploadrecord_profile_uploadrecord_user'),
        ('users', '0008_tutorprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrecord',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='user',
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='users.profile')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uploads.uploadrecord')),
            ],
        ),
    ]
