# Generated by Django 5.1.6 on 2025-03-05 22:18

from django.db import migrations, models

def generate_non_nullable_fields(apps, schema):
    upload_record_model = apps.get_model('uploads', 'UploadRecord')
    for upload in upload_record_model.objects.all():
        base_value = f"{upload.name.replace(' ', '-')}-{upload.id}"
        upload.resource_type = base_value
        upload.type = base_value
        upload.version = 0
        upload.save()


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_remove_uploadrecord_upload_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrecord',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='uploadrecord',
            name='upload',
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='resource_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='version',
            field=models.PositiveBigIntegerField(null=True),
        ),

        # add this below with your function to populate the field
        migrations.RunPython(generate_non_nullable_fields),

        migrations.AlterField(
            model_name='uploadrecord',
            name='resource_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='version',
            field=models.PositiveBigIntegerField(),
        ),
    ]
