# Generated by Django 5.1.6 on 2025-03-26 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_remove_uploadrecord_public_id_and_more'),
        ('users', '0009_alter_tutorprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='profile',
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.profile'),
            preserve_default=False,
        ),
    ]
