# Generated by Django 5.1.6 on 2025-04-10 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_alter_uploadrecord_profile'),
        ('users', '0009_alter_tutorprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrecord',
            name='profile',
        ),
        migrations.AddField(
            model_name='profilepicture',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='users.profile'),
        ),
    ]
