# Generated by Django 5.1.6 on 2025-03-08 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquizanswers',
            name='isCorrect',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='gradedAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submissionStatus',
            field=models.CharField(default='Not Submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submittedAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
