# Generated by Django 5.1.6 on 2025-03-13 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_studentquizanswers_iscorrect_and_more'),
        ('uploads', '0004_remove_uploadrecord_profile_uploadrecord_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesubmissions',
            options={'verbose_name': 'File Submission', 'verbose_name_plural': 'File Submissions'},
        ),
        migrations.AlterModelOptions(
            name='quizsubmissions',
            options={'verbose_name': 'Quiz Submission', 'verbose_name_plural': 'Quiz Submissions'},
        ),
        migrations.AlterModelOptions(
            name='studentquizanswers',
            options={'verbose_name': 'Student Quiz Answer', 'verbose_name_plural': 'Student Quiz Answers'},
        ),
        migrations.AlterModelOptions(
            name='submissions',
            options={'verbose_name_plural': 'Submissions'},
        ),
        migrations.AddField(
            model_name='filesubmissions',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploads.uploadrecord'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submissionStatus',
            field=models.CharField(default='not_submitted', max_length=50),
        ),
    ]
