# Generated by Django 5.1.6 on 2025-03-20 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_subject_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('subjects', models.ManyToManyField(blank=True, to='search.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_filters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
