# Generated by Django 5.1.6 on 2025-04-28 08:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_status'),
        ('users', '0013_alter_studentprofile_parent_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_others', to='users.profile')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='got_reported', to='users.profile')),
            ],
            options={
                'verbose_name': 'Reported User',
                'verbose_name_plural': 'Reported Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_others', to='users.profile')),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='got_blocked', to='users.profile')),
            ],
            options={
                'verbose_name': 'Blocked User',
                'verbose_name_plural': 'Blocked Users',
                'ordering': ['-created_at'],
                'unique_together': {('blocked_user', 'blocked_by')},
            },
        ),
        migrations.CreateModel(
            name='MutedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('muted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_others', to='users.profile')),
                ('muted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='got_muted', to='users.profile')),
            ],
            options={
                'verbose_name': 'Muted User',
                'verbose_name_plural': 'Muted Users',
                'ordering': ['-created_at'],
                'unique_together': {('muted_user', 'muted_by')},
            },
        ),
    ]
