# Generated by Django 5.1.7 on 2025-03-21 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('description', models.TextField()),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=50)),
                ('drop_rate', models.FloatField()),
            ],
            options={
                'verbose_name': 'Pet Catalog',
                'verbose_name_plural': 'Pet Catalogs',
            },
        ),
        migrations.CreateModel(
            name='PetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('pet_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomodoro.petcatalog')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Collection',
                'verbose_name_plural': 'Pet Collections',
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=25)),
                ('is_completed', models.BooleanField(default=False)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('pet_earned', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pomodoro Session',
                'verbose_name_plural': 'Pomodoro Sessions',
            },
        ),
    ]
