# Generated by Django 5.1.7 on 2025-03-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcatalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images'),
        ),
    ]
