# Generated by Django 5.1.6 on 2025-03-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_alter_petcatalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
