# Generated by Django 5.1.6 on 2025-04-26 11:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_pomodorosession_is_paused'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcatalog',
            name='drop_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='duration',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='petcollection',
            unique_together={('student', 'pet_catalog')},
        ),
    ]
