# Generated by Django 5.1.6 on 2025-03-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_assignment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text='Points assigned to this question'),
        ),
    ]
