# Generated by Django 5.1.6 on 2025-03-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_quiz_options_alter_assignment_assignment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit for the quiz (in minutes)', null=True),
        ),
    ]
