# Generated by Django 5.1.6 on 2025-03-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_quiz_time_limit'),
        ('uploads', '0004_remove_uploadrecord_profile_uploadrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='upload_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.uploadrecord'),
        ),
    ]
