# Generated by Django 5.1.6 on 2025-04-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_assignment_upload_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='choices',
            field=models.ManyToManyField(blank=True, help_text='Make sure the choice question number matches.', to='lessons.choice'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='short_answer_text',
            field=models.TextField(blank=True, help_text='If the question is a SA, pick any choice and fill in the text box.', null=True),
        ),
    ]
