# Generated by Django 5.1.6 on 2025-04-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_solution_choices_and_more'),
        ('lessons', '0008_assignment_reminder_sent'),
    ]

    operations = [
    ]
