name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # Set the default working directory

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install Redis
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          sudo service redis-server start
          sudo service redis-server status

      - name: Install Flake8 and Run Linter
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Coverage
        run: |
          pip install coverage

      - name: Create .env File
        run: |
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
        shell: bash

      - name: Run Migrations
        run: python manage.py migrate

      - name: Run Tests with Coverage
        run: |
          coverage run manage.py test
          coverage report
          coverage html  # Generates the HTML report in 'htmlcov' directory

      # Upload coverage HTML report as artifact
      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: backend/htmlcov/  # Upload the entire 'htmlcov' directory

