name: ReactJS CI/CD

on:
  push:
    branches:
      - adding-to-ci-pipeline # changing this temp from main to my current branch

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ensure we are in the root directory of the repo (DEBUG)
      - name: Ensure we're in the root directory
        run: |
          echo "Current working directory:"
          pwd  # This prints the current directory to the logs, confirming we're in the root

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint and auto-fix syntax/style errors
        run: npx eslint --config ./frontend/eslint.config.js --fix frontend

      # Applies syntax/style fixes from ESLint as a commit
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-fix ESLint issues"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}