# Generated by Django 5.1.6 on 2025-04-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_merge_20250419_2347'),
        ('planner', '0002_calendarevent_location_calendarevent_virtual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnscheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_assignment', models.ForeignKey(blank=True, help_text='Optionally link this task to an existing assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.assignment')),
            ],
            options={
                'verbose_name': 'Unscheduled Task',
                'verbose_name_plural': 'Unscheduled Tasks',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
